spring:
  datasource:
    url: jdbc:mysql://brx4u9itxncom7cbg7ww-mysql.services.clever-cloud.com:3306/brx4u9itxncom7cbg7ww
    username: ujqdti9sf6forgkt
    password: MbxtHec1mfcVN3LULymL
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        naming:
          physical:
            strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl